import re
import os
import shutil
from argon2 import PasswordHasher, exceptions


def has_special_char(text):
    # check for characters that are not alphabetical, numerical, or an underscore
    pattern = r'[^a-zA-Z0-9_]'
    return bool(re.search(pattern, text))


def is_valid_password(password):
    # password is at least 8 chars
    if len(password) < 8:
        print("Password must be at least 8 characters long")
        return False
    # password must have a special char
    if not has_special_char(password):
        print("Password must have a special character")
        return False
    return True


def get_hash(username):
    # retrieve hashed password
    try:
        with open(f"users/{username}/pass.bin", "r") as file:
            return file.readline()
    except FileNotFoundError:
        return None


def check_password(ph, hashed, password):
    # verify password is correct
    try:
        ph.verify(hashed, password)
        return True
    except exceptions.VerifyMismatchError:
        return False


class AccountManager:
    def __init__(self, username=None):
        self.__username = username

    # returns True if success, False if fail
    def add_account(self, username, password):
        # username is at least 4 chars
        if len(username) < 4:
            print("Username must be at least 4 characters long")
            return False

        # username must not have special char
        if has_special_char(username):
            print("Username cannot have a special character")
            return False

        if not is_valid_password(password):
            return False

        # check if username already exists
        try:
            os.mkdir(f"users/{username}")
            os.mkdir(f"users/{username}/data")
            print("Directory created")
        except FileExistsError:
            print("Username already exists")
            return False

        # store password as a hash
        with open(f"users/{username}/pass.bin", "wb") as file:
            ph = PasswordHasher()
            hashed = ph.hash(password)
            file.write(hashed.encode("utf-8"))

        print("Account created successfully")
        self.__username = username

        return True

    def delete_account(self, username, password):
        # verify username
        hashed = get_hash(username)
        if hashed is None:
            print("Username does not exist")
            return False

        # verify password
        ph = PasswordHasher()
        if check_password(ph, hashed, password):
            # delete user files
            shutil.rmtree(f"users/{username}")
            self.__username = None
            print("Account successfully deleted")
            return True
        else:
            print("Password is incorrect")
            return False

    def login(self, username, password):
        # verify username
        hashed = get_hash(username)
        if hashed is None:
            print("Username or password is incorrect")
            return False

        # verify password
        ph = PasswordHasher()
        if check_password(ph, hashed, password):
            # login
            self.__username = username
            print("Successfully logged in!")
            return True
        else:
            print("Username or password is incorrect")
            return False

    def change_password(self, username, old_password, new_password):
        if not self.login(username, old_password):
            print("Invalid username or password")
            return False

        if old_password == new_password:
            print("New password must not be the same as old password!")
            return False

        if not is_valid_password(new_password):
            return False

        with open(f"users/{username}/pass.bin", "wb") as file:
            file.truncate()
            ph = PasswordHasher()
            hashed = ph.hash(new_password)
            file.write(hashed.encode("utf-8"))

        print("Password successfully changed!")
        return True

    def get_history_log(self):
        """Reads history log into a list
        :return: a list of strings representing history items from oldest to most recent
        """
        history = []
        with open(f"{self.__username}/data/history_log.txt", "r") as log:
            item = log.readline()
            while item != "":
                history.append(item[:-1])
                item = log.readline()
        return history

    def add_history_item(self, item_name, graph_displayer):
        """Adds item to user history
        Assumptions: code is stored in submission.py, graph has been generated by graph_displayer
        :param item_name: string filename w/o extension (e.g. bubble_sort)
        :param graph_displayer: GraphDisplayer object
        """
        shutil.copy(f"{self.__username}/data/submission.py", f"{self.__username}/data/code/{item_name}.py")  # save code
        graph_displayer.save_graph(f"{self.__username}/data/graphs/{item_name}.png")  # save graph
        with open(f"{self.__username}/data/history_log.txt", "a") as log:  # write to log
            log.write(item_name + "\n")

    def delete_history_item(self, item_name):
        """Deletes item (including code and graph) from user history
        :param item_name: string filename w/o extension (e.g. bubble_sort)
        """
        os.remove(f"{self.__username}/data/code/{item_name}.py")  # delete code
        os.remove(f"{self.__username}/data/graphs/{item_name}.png")  # delete graph
        with open(f"{self.__username}/data/history_log.txt", "r") as log:  # delete from log
            log_data = log.read()
        with open(f"{self.__username}/data/history_log.txt", "w") as log:
            log.write(log_data.replace(f"{item_name}\n", ""))

    def clear_history(self):
        """Removes all history data"""
        shutil.rmtree(f"{self.__username}/data/code")  # delete all data
        shutil.rmtree(f"{self.__username}/data/graphs")
        with open(f"{self.__username}/data/history_log.txt", "w") as log:  # clear history log
            log.write("")
        os.mkdir(f"{self.__username}/data/code")  # create empty directories
        os.mkdir(f"{self.__username}/data/graphs")


# test
def main():
    am = AccountManager()
    # am.add_account("User", "User123!")
    # am.delete_account("User", "User123!")
    # am.login("User", "User123!")
    # am.change_password("User", "User123!", "User321!")


main()
