import shutil
import os


class FileHandler:
    def __init__(self, username):
        self.username = username

    def get_history_log(self):
        """Reads history log into a list
        :return: a list of strings representing history items from oldest to most recent
        """
        history = []
        with open(f"{self.username}/data/history_log.txt", "r") as log:
            item = log.readline()
            while item != "":
                history.append(item[:-1])
                item = log.readline()
        return history

    def add_history_item(self, item_name, graph_displayer):
        """Adds item to user history
        Assumptions: code is stored in submission.py, graph has been generated by graph_displayer
        :param item_name: string filename w/o extension (e.g. bubble_sort)
        :param graph_displayer: GraphDisplayer object
        """
        shutil.copy(f"{self.username}/data/submission.py", f"{self.username}/data/code/{item_name}.py")  # save code
        graph_displayer.save_graph(f"{self.username}/data/graphs/{item_name}.png")  # save graph
        with open(f"{self.username}/data/history_log.txt", "a") as log:  # write to log
            log.write(item_name + "\n")

    def delete_history_item(self, item_name):
        """Deletes item (including code and graph) from user history
        :param item_name: string filename w/o extension (e.g. bubble_sort)
        """
        os.remove(f"{self.username}/data/code/{item_name}.py")  # delete code
        os.remove(f"{self.username}/data/graphs/{item_name}.png")  # delete graph
        with open(f"{self.username}/data/history_log.txt", "r") as log:  # delete from log
            log_data = log.read()
        with open(f"{self.username}/data/history_log.txt", "w") as log:
            log.write(log_data.replace(f"{item_name}\n", ""))
